### PR TITLE
Add absolute vhost for vhost scan

### PR DESCRIPTION
**Pull request by mprunet**
This pull request add the possibility to use absolute Vhost name in order to test domains without any similarities

### CODE REVIEW

**Review by shelld3v — CHANGES_REQUESTED** [review]
The argument name is really ugly

**Comment by mprunet** [comment]
What do you think of fqdn for fully qualified domain name ?

**Comment by shelld3v** [comment]
Well, good idea!

**Comment by firefart** [comment]
this is currently implemented by the `--append-domain` parameter

**Pull request closed without merging**
