### PR TITLE
Domain Replacement

### PR DESCRIPTION
**Pull request by vysecurity**

### CODE REVIEW

**Comment by vysecurity** [comment]
Code adds a `-dr` flag which allows you to specify a word such as {{DOMAIN}}, and it will replace {{DOMAIN}} in the wordlist with the current accessed domain.

**Comment by vysecurity** [comment]
*USAGE*

List.txt:
```{{DOMAIN}}.tar.gz```

Command:
```gobuster -w list.txt -u domain.com -dr {{DOMAIN}}```

**Comment by OJ** [comment]
There's a bunch of conflicts mate. Did you base your work off the right branch?

**Comment by vysecurity** [comment]
😨 can revamp and sort it out later

**Pull request closed without merging**
