### PR TITLE
Add feature load http headers from file

### PR DESCRIPTION
**Pull request by minight**
Allows the user to specify http headers to send with dirbusting requests using a file. Useful when testing thick client web APIs that require some proprietary headers. Was unsure of whether to use cmdline arguments (like curl) or an arbitrary file. 

Usage:
```
gobuster -u http://google.com/ -hf /tmp/header.file -w ~/wordlist/Filenames_or_Directories_All.wordlist -e
```

header.file:
```
Host: google.com
Accept: */*
User-Agent: foo
X-Proprietary-Header: bar
Authorization: Bearer <some jwt>
```

### CODE REVIEW

**Comment by OJ** [comment]
Great idea, thank you for the submission! I will aim to get this locked away with a couple of other PRs very soon. Cheers :+1:

**Comment by 0xdevalias** [comment]
Potentially related, may be relevant to consider with regards to this PR:
* https://github.com/OJ/gobuster/pull/76

**Comment by codingo** [comment]
@minight nudging you on this one. I've been tunneling through burp for this on various bounty programs which enforce headers, which isn't ideal. Definitely has value!

**Comment by OJ** [comment]
Apologies for the delay on this, can I please request that you rebase your changes on 2.0.0 now that I've finally landed #79? Thank you so much.

**Comment by OJ** [comment]
I think this is superceded by the new `-H` flag. It doesn't load headers from file but at least you can wire them in on the command line.

Feel free to adjust and reopen if you think I'm wrong, but I'm going to close this one up for now. Cheers!

**Comment by OJ** [comment]
Hmm.. I realise that CLI means you can blow command line length limits with big JWTs.

So yeah, might need to have this in a file. Are you happy to rebase this on master as it currently stands please? There's been a lot of changes recently. Thank you!

**Comment by FireFart** [comment]
Closing because of no response. If you want to rebase it feel free to reopen the PR

**Pull request closed without merging**
