### PR TITLE
Verbose DNS mode to show missing values

### PR DESCRIPTION
**Pull request by g0tmi1k**
...Prob not the best way to go about doing this (open to suggestions).

### CODE REVIEW

**Comment by OJ** [comment]
It's cheeky, but I think it's fine :) I'll add a comment to the line so it's a bit clearer.

**Comment by OJ** [comment]
Actually, I'm having second thoughts about this. I like verbose mode to show me the IPs, but I don't want the output to show me all of the missing DNS names at the same time.

Might have to change this up so that verbose does what it does with `dir` mode and add another flag to show IPs.

**Comment by OJ** [comment]
I've merged this, but also doctored is as part of https://github.com/OJ/gobuster/commit/d54b3c44b3d54aa87bb80b404cb95d238f09341f -- not sure why it didn't auto close as "merged".

Cheers!

**Comment by g0tmi1k** [comment]
Good calling!
Closing rather than merging helps to cover up my mistakes ;)

**Pull request closed without merging**
