### PR TITLE
Add string blacklist feature (help needed)

### PR DESCRIPTION
**Pull request by n0kovo**
I found myself needing the feature, so I've ben trying to add a function that makes Gobuster ignore replies if the body contain any strings from a user supplied list.

As it is now, it's not working and I can't for the life of me figure out why.

Running it with `--status-codes 401` i get the error:

`Error: error on parsing arguments: status-codes and status-codes-blacklist are both set, please set only one`

Even though I haven't set `--status-codes-blacklist`.

I have next to no experience in Go and I've been pulling my hair for many hours.

### CODE REVIEW

**Comment by SantiEich** [comment]
Awesome!

**Comment by abdalkreemafm** [comment]
بتاريخ الجمعة، 23 سبتمبر 2022، جاء من Santiago Hernandez <
***@***.***>:

**Comment by n0kovo** [comment]
🤔

**Comment by n0kovo** [comment]
BUMP

**Comment by n0kovo** [comment]
Kinda rude.

**Pull request closed without merging**
