### PR TITLE
Added status code 401 (Unauthorized) to the default of status codes. …

### PR DESCRIPTION
**Pull request by FrankSpierings**
Added status code 401 (Unauthorized) to the default of status codes. During CTF's we missed important directories, using the defaults.

### CODE REVIEW

**Comment by OJ** [comment]
Thanks for this PR. Seems like a reasonable change to me. I'll get this merged into the 2.0.2-working branch soon.

Cheers!

**Comment by FireFart** [comment]
:+1: from me

**Comment by OJ** [comment]
Thanks @FrankSpierings for the submission. We'll have this merged into master as part of the v2.0.2 release soon. In future, if you decide to PR again, may I please request that you submit your PR from a feature branch instead of `master`? Thanks mate, really appreciate it!

Cheers.

**Comment by FrankSpierings** [comment]
Will do! Thanks for the merge.

**Pull request merged**
