### PR TITLE
Add Feature to discover backup files.

### PR DESCRIPTION
**Pull request by IppSec**
Added the -d flag to DiscoverContent.  This will take all files with a 200 HTTP Response and then mutate the file to find backup copies.

**Example:** 
index.php ->
* index.php~
* index.php.bak
* index.bak
* .index.php.swp

### CODE REVIEW

**Comment by FireFart** [comment]
@IppSec thanks for your contribution! I think we already have this implemented in the `v3.1-working` branch over here https://github.com/OJ/gobuster/tree/v3.1-working with the new `--pattern` option:
https://github.com/OJ/gobuster/tree/v3.1-working#patterns

Does that fit?

**Comment by IppSec** [comment]
I think they are different but I don’t fully understand the pattern option.  

The main difference is this generates the wordlist based upon found files, whereas pattern applies it to everything in the dirlist.  Additionally, I don’t think patterns supports removing extension then appending items.

**Comment by FireFart** [comment]
Oh ok so it only searches backups for found files, missed that. Can you please rebase the branch on the v3.1-working branch as this is the current development version? Thanks!

**Comment by IppSec** [comment]
Created #201 to rebase against my v3.1 branch.

**Pull request closed without merging**
