### PR TITLE
attempt to solve issue #20

### PR DESCRIPTION
**Pull request by viaMorgoth**
Hoping this adds the intended extra functionality. If not, happy to modify.

### CODE REVIEW

**Comment by OJ** [comment]
Thank you for the submission! I'll review at some point today. I think I might make a couple of small style changes, but for the most part I think it's good.

I appreciate the PR, thank you :+1:

**Comment by OJ** [comment]
@viaMorgoth By the way, may I please request that future pull requests be made from a feature branch instead of from `master`? Thanks!

**Comment by viaMorgoth** [comment]
Sure will, sorry abut that. I'm no uber programmer so I'm looking forward to seeing the style changes you make :) BTW I'm happy to help with anything else on this project. I've been trying to find ways to learn Go a bit better.

**Comment by OJ** [comment]
@viaMorgoth No need to apologise, we all start learning at the beginning! It's just good practice to do that, as it means that any other merges you make into your own master branch don't end up in this pr :) 

Thank you for the contribution. I've merged it into master. Cheers!

**Pull request merged**
